/* 쿠버네티스 항구 — 설명 내용: 겹 1(말풍선·자막) · 겹 2(패널) · 겹 3(실제로는?) · 이름 규칙 */
(function(){
"use strict";

var ACTORS = {
  hill:{ name:"관제 언덕", real:"Control Plane", hero:false,
    tip:"클러스터의 '두뇌'가 모인 곳이에요. 무엇을 어디서 돌릴지 여기서 정해요.",
    what:"관제탑 접수 창구, 금고 장부, 순찰 로봇, 크레인 배치원이 모두 이 소속이에요. 이들은 직접 컨테이너를 돌리지 않고, <b>결정하고 기록하는 일</b>만 해요. 실제 실행은 부두(Worker Node)가 맡아요.",
    talks:[["부두 반장 (kubelet)","HTTPS","할 일을 알려 주고 보고를 받음"],["사람 (kubectl)","HTTPS","요청을 받음"]],
    steps:["요청 접수 (apiserver)","장부에 기록 (etcd)","차이 발견·조치 (controller-manager)","자리 결정 (scheduler)"],
    xr:[{l:"구성 요소 확인", code:"<span class='k'>$ kubectl get pods -n kube-system</span>\netcd-cp-1                      1/1  Running\nkube-apiserver-cp-1            1/1  Running\nkube-controller-manager-cp-1   1/1  Running\nkube-scheduler-cp-1            1/1  Running"}],
    myth:"Control Plane도 컨테이너를 돌린다? — 보통은 앱 컨테이너를 받지 않도록 막아 둬요(taint). 결정만 하는 쪽이에요." },

  tower:{ name:"관제탑 접수 창구", real:"kube-apiserver",
    tip:"항구의 유일한 출입구예요. 모든 요청과 보고가 여기를 지나가요.",
    what:"사람의 요청도, 로봇·크레인·반장의 조회와 보고도 전부 이 창구를 거쳐요. <b>금고 장부와 직접 이야기할 수 있는 것도 창구뿐</b>이에요. 창구는 검사하고 기록하고 알려 줄 뿐, 직접 무언가를 실행하지는 않아요.",
    talks:[["배포 사무소 (kubectl)","HTTPS · REST","원하는 상태를 제출·조회"],["금고 장부 (etcd)","gRPC","저장·읽기"],["로봇·크레인·반장","HTTPS watch","바뀐 것을 알려 주고 보고를 받음"]],
    steps:["신원 확인 — 인증 (Authentication)","권한 확인 — 인가 (RBAC)","빠진 기본값 채우기 (defaulting)","규칙 확인 — 승인 제어 (Admission: 변경 → 검증)","형식 검증","장부에 저장","지켜보는 쪽에 변경 알림 (watch)"],
    xr:[{l:"창구 상태 확인", code:"<span class='k'>$ kubectl get --raw='/readyz?verbose'</span>\n[+]etcd ok\n[+]informer-sync ok\nreadyz check passed"},
          {l:"모든 요청이 실제로는 HTTP 요청이에요", code:"<span class='k'>$ kubectl get pods -v=6</span>\n<span class='c'>GET https://10.0.0.10:6443/api/v1/namespaces/default/pods 200 OK</span>"}],
    myth:"창구가 컨테이너를 실행한다? — 아니에요. 기록하고 알릴 뿐이고, 실행은 부두 반장(kubelet)이 해요." },

  vault:{ name:"금고 장부", real:"etcd",
    tip:"항구의 모든 기록이 적힌 단 하나의 원본 장부예요.",
    what:"어떤 앱을 몇 개 원하는지, 어느 부두에 무엇이 있는지 같은 <b>클러스터의 모든 상태</b>가 키-값으로 저장돼요. 보통 금고를 3대 두고, 과반수가 동의해야 기록이 확정돼요(Raft 합의).",
    talks:[["관제탑 접수 창구","gRPC","읽기·쓰기·변경 감시"]],
    steps:["창구가 쓰기 요청","리더 금고가 기록 추가","다른 금고에 복제","과반수 확인 후 확정","버전 번호(revision) 증가 → 지켜보는 쪽에 통지"],
    xr:[{l:"장부 속 실제 키", code:"<span class='k'>$ etcdctl get /registry --prefix --keys-only</span>\n/registry/deployments/default/my-shop\n/registry/replicasets/default/my-shop-7d9f6c\n/registry/pods/default/my-shop-7d9f6c-4xk2p\n/registry/services/specs/default/my-shop"}],
    myth:"금고가 꺼지면 컨테이너가 다 멈춘다? — 이미 돌던 컨테이너는 계속 돌아요. 대신 새 배포나 복구가 전부 멈춰요." },

  robot:{ name:"순찰 로봇", real:"kube-controller-manager",
    tip:"장부의 '원하는 수'와 '현재 수'를 계속 비교하고, 차이를 메우는 로봇이에요.",
    what:"누구의 명령도 받지 않아요. 창구를 통해 장부를 <b>지켜보다가(watch)</b> 원하는 상태와 현재 상태가 다르면 그 차이만큼 만들거나 지워요. 실제로는 Deployment·ReplicaSet·Node 등 수십 개 로봇이 한 프로세스에 들어 있어요.",
    talks:[["관제탑 접수 창구","HTTPS watch","변경 감시, 새 기록 생성·수정"]],
    steps:["변경 감지 (watch)","원하는 상태 읽기 (spec)","현재 상태 세기 (status)","차이만큼 만들기·지우기","다시 지켜보기 — 끝없이 반복 (reconcile loop)"],
    xr:[{l:"로봇이 만든 기록 따라가기 (종류마다 표가 따로 나와요)", code:"<span class='k'>$ kubectl get deploy,rs,pod -l app=my-shop</span>\nNAME                      READY   UP-TO-DATE   AVAILABLE   AGE\ndeployment.apps/my-shop   3/3     3            3           2m\n\nNAME                             DESIRED   CURRENT   READY   AGE\nreplicaset.apps/my-shop-7d9f6c   3         3         3       2m\n\nNAME                       READY   STATUS    RESTARTS   AGE\npod/my-shop-7d9f6c-4xk2p   1/1     Running   0          2m\npod/my-shop-7d9f6c-9tq8m   1/1     Running   0          2m\npod/my-shop-7d9f6c-b2zrl   1/1     Running   0          2m"}],
    myth:"한 번 맞추면 끝난다? — 끝이 없어요. 영원히 도는 조정 루프라서 누가 컨테이너를 지워도 다시 채워져요." },

  crane:{ name:"크레인 배치원", real:"kube-scheduler",
    tip:"아직 자리가 없는 컨테이너를 보고, 어느 부두에 둘지 정해요.",
    what:"자리 미정(nodeName이 비어 있는) 컨테이너를 찾아 <b>후보 부두를 거르고(Filter), 점수를 매겨(Score), 가장 좋은 곳을 장부에 적어요(Bind)</b>. 그림에서는 크레인이 상자를 옮기지만, 실제로는 장부에 '부두 2'라고 한 줄 적는 게 전부예요.",
    talks:[["관제탑 접수 창구","HTTPS watch","자리 미정 컨테이너 감시 · 배치 결과 기록"]],
    steps:["대기열에서 하나 꺼내기","거르기 — 자원 부족·조건 불일치 부두 제외","점수 — 여유 자원·분산 정도","최고점 부두 선택","배치 결과 기록 (Binding → nodeName)"],
    xr:[{l:"배치 결과", code:"<span class='k'>$ kubectl get pod -o wide</span>\nNAME                   STATUS    NODE\nmy-shop-7d9f6c-4xk2p   Running   <span class='y'>worker-2</span>"},
          {l:"자리가 없을 때", code:"<span class='k'>$ kubectl describe pod my-shop-7d9f6c-4xk2p</span>\nEvents:\n  Type     Reason            Age   From               Message\n  ----     ------            ----  ----               -------\n  Warning  FailedScheduling  12s   default-scheduler  0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 2 Insufficient memory. <span class='c'>(… 이어지는 preemption 설명은 생략)</span>"}],
    myth:"스케줄러가 컨테이너를 부두로 보낸다? — 이름 한 줄을 적을 뿐이에요. 실제로 띄우는 건 그 부두의 반장이에요." },

  yard:{ name:"대기 구역", real:"Pending Pod (nodeName 없음)", hero:false,
    tip:"장부에는 있지만 아직 어느 부두에 둘지 정해지지 않은 컨테이너가 기다리는 곳이에요.",
    what:"로봇이 만든 컨테이너 기록은 처음에 <b>자리(nodeName)가 비어</b> 있어요. 실제로 이런 '장소'가 있는 건 아니고, 크레인 배치원의 대기열에서 차례를 기다리는 상태를 그림으로 표현한 거예요.",
    talks:[["순찰 로봇","—","기록을 만들어 둠"],["크레인 배치원","watch","꺼내서 자리를 정함"]],
    steps:["로봇이 컨테이너 기록 생성","nodeName 비어 있음 → Pending","배치원 대기열 진입","자리가 정해지면 대기열에서 빠짐"],
    xr:[{l:"자리 미정 컨테이너만 보기", code:"<span class='k'>$ kubectl get pod --field-selector spec.nodeName=</span>\nNAME                   READY   STATUS\nmy-shop-7d9f6c-4xk2p   0/1     Pending"}],
    myth:"Pending이면 오류다? — 배치를 기다리거나 이미지를 받는 중일 수도 있어요. describe의 Events로 이유를 봐요." },

  office:{ name:"배포 사무소", real:"kubectl",
    tip:"사람이 '이렇게 되어 있으면 좋겠다'를 적어 관제탑에 보내는 곳이에요.",
    what:"YAML에 <b>원하는 상태</b>(my-shop 컨테이너 3개)를 적어 창구에 보내요. '컨테이너를 실행해'라는 명령이 아니라 '3개가 있어야 해'라는 선언이에요. 어느 창구에 누구로 접속할지는 kubeconfig에 적혀 있어요.",
    talks:[["관제탑 접수 창구","HTTPS (인증서·토큰)","요청 제출·조회"]],
    steps:["kubeconfig에서 서버 주소·신분 읽기","YAML을 JSON으로 변환","창구 API로 요청","응답 출력"],
    xr:[{l:"보낸 요청서 (my-shop.yaml) — 줄마다 누가 정한 이름인지", code:"apiVersion: apps/v1          <span class='c'># 공식</span>\nkind: Deployment             <span class='c'># 공식</span>\nmetadata:\n  name: my-shop              <span class='c'># ← 직접 지은 이름</span>\nspec:\n  replicas: 3                <span class='c'># 공식 필드 · 값은 내가 정함</span>\n  selector:\n    matchLabels:\n      app: my-shop           <span class='c'># 라벨 키·값 모두 직접 지음</span>\n  template:\n    metadata:\n      labels:\n        app: my-shop\n    spec:\n      containers:\n      - name: my-shop        <span class='c'># ← 직접 지은 이름</span>\n        image: nginx:1.27    <span class='c'># 외부 이미지 이름</span>"},
          {l:"파일 이름은 상관없어요", code:"<span class='k'>$ kubectl apply -f 아무이름.yaml</span>   <span class='c'># 파일 이름은 kubectl이 신경 쓰지 않아요</span>\n<span class='c'># 쿠버네티스에 등록되는 이름은 파일 안의 metadata.name 이에요</span>"}],
    myth:"kubectl apply가 컨테이너를 띄운다? — 장부에 원하는 상태를 적는 순간 끝나요. 띄우는 건 그 뒤 다른 부품들이에요." },

  pier:{ name:"부두", real:"Worker Node", hero:false,
    tip:"컨테이너가 실제로 돌아가는 컴퓨터예요. 부두마다 반장과 하역 기계가 있어요.",
    what:"실제 서버(또는 가상 머신) 한 대예요. 부두마다 <b>반장(kubelet)</b>, <b>하역 기계(containerd)</b>, <b>길 안내 규칙(kube-proxy)</b>이 상주해요. 부두가 많을수록 더 많은 컨테이너를 둘 수 있어요.",
    talks:[["관제탑 접수 창구","HTTPS","반장이 할 일을 받고 상태를 보고"]],
    steps:["반장이 창구에 부두를 등록","배선(CNI)이 깔리면 Ready","배정된 컨테이너 실행","주기적으로 생존 신호 보고"],
    xr:[{l:"부두 목록", code:"<span class='k'>$ kubectl get nodes</span>\nNAME       STATUS   ROLES           VERSION\ncp-1       Ready    control-plane   v1.31.2\nworker-1   Ready    &lt;none&gt;          v1.31.2\nworker-2   Ready    &lt;none&gt;          v1.31.2"}],
    myth:"부두 하나에 컨테이너 하나? — 자원이 허락하는 만큼 여러 개를 둘 수 있어요." },

  foreman:{ name:"부두 반장", real:"kubelet",
    tip:"자기 부두에 배정된 컨테이너만 지켜보다가, 생기면 실행시키고 보고해요.",
    what:"모든 부두에 한 명씩 있어요. 창구를 통해 <b>'우리 부두로 배정된 컨테이너'</b>만 지켜보고, 새로 생기면 하역 기계에 실행을 지시해요. 실행 후에는 상태를 검사해서 관제탑에 계속 보고해요.",
    talks:[["관제탑 접수 창구","HTTPS watch","내 몫 감시 · 상태와 생존 신호 보고"],["하역 기계 (containerd)","CRI (gRPC)","샌드박스 만들기·이미지 받기·컨테이너 시작 — 네트워크(CNI)는 하역 기계가 샌드박스 안에서 연결"]],
    steps:["우리 부두에 배정된 컨테이너 발견","격리 공간(샌드박스) 만들기 지시 (CRI RunPodSandbox — 안에서 하역 기계가 배선 CNI 를 불러 IP 를 받음)","이미지 받기 지시 (CRI PullImage)","컨테이너 시작 지시","건강 검사 (probe)","상태 보고 · 약 10초마다 생존 신호 (Lease)"],
    xr:[{l:"반장은 컨테이너가 아니라 서버의 서비스로 돌아요", code:"<span class='k'>$ systemctl status kubelet</span>\n● kubelet.service - kubelet: The Kubernetes Node Agent\n   Active: <span class='g'>active (running)</span>"}],
    myth:"반장이 다른 부두 컨테이너도 챙긴다? — 자기 부두 몫만 봐요. 그래서 부두가 수천 개여도 창구 하나로 버틸 수 있어요." },

  machine:{ name:"하역 기계", real:"containerd (컨테이너 런타임)", hero:false,
    tip:"반장의 지시를 받아 이미지를 받아 오고 컨테이너를 실제로 켜는 기계예요.",
    what:"반장과는 <b>CRI라는 표준 규격</b>으로 대화해요. 규격만 맞으면 다른 기계(CRI-O)로 바꿔도 돼요. 실제 격리는 runc가 리눅스 namespace·cgroup으로 만들어요.",
    talks:[["부두 반장 (kubelet)","CRI (gRPC)","RunPodSandbox · PullImage · StartContainer"],["이미지 저장소","HTTPS","이미지 레이어 받기"]],
    steps:["이미지 레이어 받기","파일시스템 준비 (snapshot)","runc가 격리 공간 생성","프로세스 시작"],
    xr:[{l:"기계에게 직접 물어보기", code:"<span class='k'>$ sudo crictl ps</span>\nCONTAINER     IMAGE        STATE     NAME   POD\n3f1a9c2e7b0d  nginx:1.27   <span class='g'>Running</span>   my-shop    my-shop-7d9f6c-4xk2p"}],
    myth:"쿠버네티스에는 Docker가 필수다? — CRI 규격을 지키는 런타임이면 돼요. 1.24부터 Docker 직접 연결은 빠졌어요." },

  pod:{ name:"컨테이너 묶음", real:"Pod", hero:false,
    tip:"쿠버네티스가 다루는 가장 작은 배포 단위예요. 그림의 상자 하나가 Pod 하나예요.",
    what:"Pod 안에는 컨테이너가 <b>하나 이상</b> 들어갈 수 있고, 같은 Pod의 컨테이너는 IP 하나와 저장 공간을 나눠 써요. Pod는 고쳐 쓰지 않는 소모품이에요. 문제가 생기면 지우고 새로 만들어요.",
    talks:[["같은 Pod의 다른 컨테이너","localhost","네트워크 공유"],["다른 Pod","Pod IP · Service","배선(CNI)으로 연결"]],
    steps:["Pending — 자리 미정 또는 준비 중","ContainerCreating — 이미지 받는 중","Running — 실행 중","Succeeded / Failed — 종료"],
    xr:[{l:"Pod 하나 자세히 보기", code:"<span class='k'>$ kubectl describe pod my-shop-7d9f6c-4xk2p</span>\nNode:    worker-2/10.0.0.12\nStatus:  Running\nIP:      10.244.2.4\nContainers:\n  my-shop:  Image: nginx:1.27"}],
    myth:"점선 상자도 실제로 존재한다? — 점선은 장부에만 있는 기록이에요. 반장이 실행해야 색이 채워진 진짜 상자가 돼요." },

  ship:{ name:"이미지 저장소선", real:"Container Registry", hero:false,
    tip:"컨테이너의 재료(이미지)를 싣고 있는 배예요. 하역 기계가 필요할 때 받아 가요.",
    what:"Docker Hub, ECR, Harbor 같은 이미지 저장소예요. 쿠버네티스 바깥에 있고, 하역 기계가 <b>이미지 이름(nginx:1.27)</b>으로 찾아서 받아 와요. 이름이 틀리면 받지 못해 컨테이너가 시작되지 않아요.",
    talks:[["하역 기계 (containerd)","HTTPS","이미지 레이어 전달"]],
    steps:["하역 기계가 이미지 이름으로 요청","레이어 목록 (manifest) 전달","부두에 없는 레이어만 전송"],
    xr:[{l:"이름이 틀렸을 때", code:"Warning  Failed  Failed to pull image \"ngin:1.27\":\n         pull access denied, repository does not exist\nWarning  Failed  Error: <span class='y'>ImagePullBackOff</span>"}],
    myth:"매번 이미지를 처음부터 받는다? — 부두에 이미 있는 레이어는 다시 받지 않아요." },

  cni:{ name:"배선", real:"CNI plugin (Calico · Cilium · Flannel)", hero:false,
    tip:"컨테이너마다 주소(IP)를 붙이고 부두끼리 통하게 하는 배선이에요.",
    what:"쿠버네티스는 '컨테이너마다 IP가 있고 서로 바로 통해야 한다'는 <b>규격만</b> 정해요. 실제 배선 공사는 Calico·Cilium 같은 플러그인이 해요. 배선이 없으면 부두는 Ready가 되지 못해요.",
    talks:[["하역 기계 (RunPodSandbox 안에서)","CNI (ADD / DEL)","컨테이너 네트워크 연결·해제"]],
    steps:["ADD 요청 받음","가상 랜선(veth) 한 쌍 생성","부두 몫 주소 대역에서 IP 할당","부두 간 길(라우팅·터널) 설정"],
    xr:[{l:"받은 IP 확인", code:"<span class='k'>$ kubectl get pod -o wide</span>\nNAME                   IP           NODE\nmy-shop-7d9f6c-4xk2p   <span class='y'>10.244.2.4</span>   worker-2\nmy-shop-7d9f6c-9tq8m   <span class='y'>10.244.1.5</span>   worker-1"}],
    myth:"쿠버네티스가 네트워크를 기본 제공한다? — 규격만 있어요. 플러그인을 따로 설치해야 해요." },

  booth:{ name:"안내소", real:"CoreDNS",
    tip:"이름(my-shop)을 물으면 고정 우편함 주소를 알려 줘요. '손님 요청 보내기' 사건에서 활약해요.",
    what:"클러스터 안의 이름 <b>my-shop.default.svc.cluster.local</b>을 고정 주소(ClusterIP)로 바꿔 줘요. 안내소 자신도 Pod로 돌아요.",
    talks:[["컨테이너","DNS (UDP 53)","이름 질의"],["관제탑 접수 창구","HTTPS watch","우편함 목록 감시"]],
    steps:["컨테이너가 my-shop을 질의","도메인 붙여 확장","우편함 목록에서 찾기","고정 주소 응답"],
    xr:[{l:"이름 물어보기", code:"<span class='k'>$ kubectl exec -it order -- nslookup my-shop</span>\nName:    my-shop.default.svc.cluster.local\nAddress: 10.96.0.12"}],
    myth:"DNS가 컨테이너 IP를 돌려준다? — 보통은 바뀌지 않는 우편함 주소(ClusterIP)를 줘요." },

  mailbox:{ name:"고정 우편함", real:"Service (ClusterIP)",
    tip:"컨테이너 주소는 계속 바뀌니, 바뀌지 않는 대표 주소를 하나 둬요. '손님 요청 보내기' 사건에서 활약해요.",
    what:"같은 라벨(app=my-shop)을 가진 컨테이너 묶음 앞에 <b>고정 IP와 이름</b>을 붙여요. 우편함으로 온 요청은 부두마다 깔린 길 안내 규칙(kube-proxy)이 살아 있는 컨테이너 하나로 보내요.",
    talks:[["안내소 (CoreDNS)","—","이름 등록"],["길 안내 규칙 (kube-proxy)","—","고정 주소 → 컨테이너 주소 규칙"]],
    steps:["라벨로 컨테이너 고르기","살아 있는 컨테이너 IP 목록 유지 (EndpointSlice)","고정 주소 배정"],
    xr:[{l:"우편함 뒤의 실제 주소들", code:"<span class='k'>$ kubectl get endpointslice -l kubernetes.io/service-name=my-shop</span>\nNAME            ADDRESSES\nmy-shop-x7k2q   10.244.1.5,10.244.2.4,10.244.2.5"}],
    myth:"우편함이 요청을 받아 전달하는 서버다? — 가상 주소예요. 실제 전달은 각 부두 커널의 규칙이 해요." }
};

/* 사건: 앱 배포하기 */
var DEPLOY_BEATS = [
  { actor:"office",
    text:"배포 사무소에서 요청서(<b>my-shop.yaml</b>)를 관제탑으로 보내요. 요청서에는 '컨테이너를 켜라'가 아니라 <b>'my-shop 컨테이너가 3개 있어야 한다'</b>는 원하는 상태가 적혀 있어요.",
    xray:[{l:"실행한 명령", code:"<span class='k'>$ kubectl apply -f my-shop.yaml</span>"},
          {l:"실제로 나간 HTTP 요청", code:"POST https://10.0.0.10:6443\n     /apis/apps/v1/namespaces/default/deployments\nContent-Type: application/json\n{ \"kind\": \"Deployment\", \"spec\": { <span class='y'>\"replicas\": 3</span>, … } }"}] },
  { actor:"tower",
    text:"관제탑 접수 창구가 요청서를 검사해요. <b>누가 보냈는지</b>, <b>그럴 권한이 있는지</b>, <b>규칙에 맞는지</b> — 도장 세 개를 모두 받아야 통과해요.",
    xray:[{l:"① 인증 — 누구냐", code:"클라이언트 인증서 CN=<span class='y'>dev-user</span>, O=dev  →  <span class='g'>확인</span>"},
          {l:"② 인가 — 해도 되냐 (RBAC)", code:"user=dev-user  verb=<span class='y'>create</span>  resource=deployments\nnamespace=default  →  <span class='g'>allowed</span> (RoleBinding: dev-edit)"},
          {l:"③ 기본값 채우기 · 승인 제어 — 규칙에 맞냐", code:"<span class='c'># 기본값은 API 서버가 요청을 읽을 때(defaulting) 채워요 — 승인 제어가 아니에요</span>\nstrategy, revisionHistoryLimit …  →  기본값 채워짐\n<span class='c'># 승인 제어는 그 다음: 변경(Mutating) → 검증(Validating)</span>\nMutating:   웹훅이 있으면 여기서 요청을 고쳐요 (예: 사이드카 주입)  →  이 요청은 변경 없음\nValidating: 자원 한도·정책 검사  →  <span class='g'>통과</span>"}] },
  { actor:"vault",
    text:"통과한 요청서는 <b>금고 장부</b>에 적혀요. 여기까지 오면 배포 사무소는 '접수 완료' 답을 받고 일이 끝나요. 하지만 <b>아직 컨테이너는 하나도 없어요.</b>",
    xray:[{l:"장부에 생긴 키", code:"/registry/deployments/default/my-shop\n  spec.replicas: <span class='y'>3</span>\n  status.replicas: <span class='y'>0</span>\n  metadata.resourceVersion: \"48213\""},
          {l:"사무소가 받은 응답", code:"deployment.apps/my-shop <span class='g'>created</span>"}] },
  { actor:"robot",
    text:"순찰 로봇은 늘 장부를 <b>지켜보고(watch)</b> 있어요. '원하는 수 3, 현재 0'을 발견하고, 그 차이만큼 <b>자리가 정해지지 않은 컨테이너 3개</b>를 대기 구역에 만들어요.",
    xray:[{l:"로봇이 받은 변경 알림", code:"<span class='k'>GET /apis/apps/v1/deployments?watch=true</span>\n{\"type\":\"<span class='y'>ADDED</span>\",\"object\":{\"kind\":\"Deployment\",\n  \"metadata\":{\"name\":\"my-shop\",\"resourceVersion\":\"48213\"},\n  \"spec\":{\"replicas\":3}}}"},
          {l:"ReplicaSet 이 만든 Pod 3개 — 아직 자리(nodeName)가 없다", code:"<span class='k'>$ kubectl get pod -l app=my-shop \\\n    -o custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName</span>\nNAME                   STATUS    NODE\nmy-shop-7d9f6c-4xk2p   <span class='y'>Pending</span>   &lt;none&gt;\nmy-shop-7d9f6c-9tq8m   <span class='y'>Pending</span>   &lt;none&gt;\nmy-shop-7d9f6c-b2zrl   <span class='y'>Pending</span>   &lt;none&gt;"}] },
  { actor:"crane",
    text:"크레인 배치원이 대기 중인 컨테이너를 보고 둘 곳을 정해요. 자리가 모자란 부두는 빼고, 남은 부두에 점수를 매겨 <b>가장 여유 있는 곳</b>을 골라요. 실제로 하는 일은 장부에 <b>'이 컨테이너는 부두 2'</b>라고 적는 것뿐이에요.",
    xray:[{l:"거르기 → 점수", code:"worker-1  Filter <span class='g'>통과</span>  Score 72\nworker-2  Filter <span class='g'>통과</span>  Score <span class='y'>85</span>  ← 선택"},
          {l:"기록한 배치 결과 (Binding)", code:"POST /api/v1/namespaces/default/pods/my-shop-7d9f6c-4xk2p/binding\n{ \"target\": { \"kind\": \"Node\", \"name\": \"<span class='y'>worker-2</span>\" } }"},
          {l:"결과적으로 바뀐 필드", code:"pod/my-shop-7d9f6c-4xk2p  spec.nodeName: <span class='y'>worker-2</span>"}] },
  { actor:"foreman",
    text:"각 부두 반장은 <b>'우리 부두로 배정된 컨테이너'</b>만 지켜봐요. 새 상자를 발견하면 하역 기계에 실행을 지시하고, 기계는 저장소선에서 <b>이미지(nginx:1.27)</b>를 받아 컨테이너를 켜요. 배선이 주소(IP)를 붙여요.",
    xray:[{l:"반장 → 하역 기계 (CRI 호출)", code:"RunPodSandbox   → 격리 공간 생성\n  CNI ADD       → IP <span class='y'>10.244.2.4</span> 할당\nPullImage       nginx:1.27\nCreateContainer my-shop\nStartContainer  my-shop"},
          {l:"Pod에 쌓인 이벤트", code:"<span class='k'>$ kubectl describe pod my-shop-7d9f6c-4xk2p</span>\nEvents:\n  Type    Reason     Age   From               Message\n  ----    ------     ----  ----               -------\n  Normal  Scheduled  8s    default-scheduler  Successfully assigned default/my-shop-7d9f6c-4xk2p to worker-2\n  Normal  Pulling    7s    kubelet            Pulling image \"nginx:1.27\"\n  Normal  Pulled     5s    kubelet            Successfully pulled image \"nginx:1.27\" in 2.1s\n  Normal  Created    5s    kubelet            Created container my-shop\n  <span class='g'>Normal  Started    5s    kubelet            Started container my-shop</span>"}] },
  { actor:"robot",
    text:"반장들이 '실행 중'이라고 보고하면 장부의 현재 수가 <b>3</b>이 돼요. 원하는 수와 같아졌으니 모두 다시 지켜보기만 해요. <b>누구도 서로에게 직접 지시하지 않았어요</b> — 모두 장부를 보고 자기 몫만 했어요.",
    xray:[{l:"최종 상태", code:"<span class='k'>$ kubectl get deploy my-shop</span>\nNAME      READY   UP-TO-DATE   AVAILABLE\nmy-shop   <span class='g'>3/3</span>     3            3"},
          {l:"어디에 놓였나", code:"<span class='k'>$ kubectl get pod -o wide</span>\nNAME                   STATUS    IP           NODE\nmy-shop-7d9f6c-4xk2p   Running   10.244.2.4   worker-2\nmy-shop-7d9f6c-9tq8m   Running   10.244.1.5   worker-1\nmy-shop-7d9f6c-b2zrl   Running   10.244.2.5   worker-2"}] }
];

window.CONTENT = {
  title:"쿠버네티스 항구",
  subtitle:"클러스터가 일하는 모습을 항구로 그렸어요",
  logo:"⎈",
  intro:{
    title:"이 항구가 쿠버네티스 클러스터예요",
    body:"언덕 위 <b>관제탑</b>이 무엇을 할지 결정하고, 바다 쪽 <b>부두</b>들이 실제로 일해요.<br>왼쪽 아래 버튼으로 사건을 일으키면 항구가 어떻게 반응하는지 볼 수 있어요.",
    sub:"궁금한 건물이나 인물은 언제든 눌러 보세요. 누를수록 더 깊이 들어갑니다."
  },
  actors:ACTORS,
  events:[
    {id:"deploy", icon:"📦", title:"앱 배포하기", sub:"요청서 한 장이 컨테이너가 되기까지", beats:DEPLOY_BEATS},
    {id:"request", icon:"✉️", title:"손님 요청 보내기", ready:false, beats:[]},
    {id:"scale", icon:"➕", title:"컨테이너 늘리기", ready:false, beats:[]},
    {id:"nodedown", icon:"⚡", title:"부두 하나 끄기", ready:false, beats:[]}
  ],
  names:{
    examples:{o:"kubelet", c:"my-shop", a:"-7d9f6c-4xk2p"},
    official:["apiVersion","kind","metadata","name","spec","replicas","selector","matchLabels","labels","template","containers","image",
      "status","nodeName","resourceVersion","Deployment","ReplicaSet","Pod","Node","Binding","RoleBinding","Service","EndpointSlice","ClusterIP",
      "Running","Pending","ContainerCreating","ImagePullBackOff","ErrImagePull","Ready","NotReady","Scheduled","Pulling","Pulled","Created",
      "Started","Failed","BackOff","FailedScheduling","Warning","Normal","default","kube-system","kube-apiserver","kube-scheduler",
      "kube-controller-manager","kubelet","etcd","control-plane","deployment.apps","replicaset.apps","deployments","replicasets","pods",
      "namespaces","target","RunPodSandbox","PullImage","CreateContainer","StartContainer","kubectl","kubernetes.io","ADDED","Lease",
      "Control Plane","Worker Node","kube-proxy","Filter","Score","Bind","watch","reconcile loop","RBAC","Admission","Authentication",
      "kubeconfig","CNI","CRI","CSI","probe","liveness","readiness","taint","node-role.kubernetes.io","Ingress","Ingress Controller","headless Service","HPA",
      "PV","PVC","namespace","metadata.name","spec.nodeName","Succeeded","Node condition"],
    projects:["containerd","CoreDNS","Calico","Cilium","Flannel","CRI-O","runc","ingress-nginx","Metrics Server","Prometheus"],
    custom:{"my-shop.yaml":"cfile", "my-shop":"c", "app":"c", "dev-user":"cuser", "dev-edit":"cuser", "worker-1":"cnode", "worker-2":"cnode",
      "cp-1":"cnode", "nginx:1.27":"cimg", "ngin:1.27":"cimg"},
    auto:{"48213":"arv", "3f1a9c2e7b0d":"acid", "10.0.0.10":"caddr", "10.0.0.12":"caddr"},
    /* 직접 지은 부분과 자동으로 붙은 부분이 한 단어에 섞인 이름은 쪼개서 칠한다 */
    patterns:[
      {re:"(?:etcd|kube-apiserver|kube-controller-manager|kube-scheduler)-cp-1", parts:function(m){ return [["o","o",m.slice(0,-5)], ["c","cnode","-cp-1"]]; }},
      {re:"my-shop\\.default\\.svc\\.cluster\\.local", parts:function(m){ return [["c","c","my-shop"], ["o","o",m.slice(7)]]; }},
      {re:"my-shop-[0-9a-f]{6}-[a-z0-9]{5}", parts:function(m){ return [["c","c","my-shop"], ["a","ars",m.slice(7,14)], ["a","apod",m.slice(14)]]; }},
      {re:"my-shop-[0-9a-f]{6}", parts:function(m){ return [["c","c","my-shop"], ["a","ars",m.slice(7)]]; }},
      {re:"my-shop-[a-z0-9]{5}", parts:function(m){ return [["c","c","my-shop"], ["a","aes",m.slice(7)]]; }},
      {re:"10\\.244\\.\\d+\\.\\d+", parts:function(m){ return [["a","aip",m]]; }},
      {re:"10\\.96\\.\\d+\\.\\d+", parts:function(m){ return [["a","acip",m]]; }}
    ],
    messages:{
      o:"<b>공식 용어</b> · 쿠버네티스가 정한 이름이라 그대로 써야 해요.",
      oext:"<b>공식 이름</b> · 쿠버네티스와 함께 쓰는 프로젝트의 정식 이름이에요. 그대로 써요.",
      cfile:"<b>직접 지은 파일 이름</b> · kubectl은 파일 이름을 신경 쓰지 않아요. 쿠버네티스에 등록되는 이름은 파일 안의 metadata.name이에요.",
      cnode:"<b>직접 정한 이름</b> · 노드 이름은 보통 서버의 호스트 이름을 그대로 써요.",
      caddr:"<b>외부가 정한 값</b> · 서버(관제탑·부두)의 주소예요. 쿠버네티스가 아니라 서버를 빌린 곳(클라우드·사내 네트워크)이 배정해요.",
      cuser:"<b>직접 정한 이름</b> · 사용자와 권한 묶음 이름은 관리자가 정해요.",
      cimg:"<b>골라서 적은 이미지 이름</b> · 이미지 저장소에 있는 이름을 골라 적은 거예요.",
      ars:"<b>자동 생성</b> · Pod 설계도(template)로 계산한 해시예요. 설계도가 바뀌면 이 값도 바뀌어요. (ReplicaSet 이름에 붙음)",
      apod:"<b>자동 생성</b> · Pod마다 붙는 무작위 5글자예요. 같은 이름이 겹치지 않게 해요.",
      aes:"<b>자동 생성</b> · EndpointSlice에 붙는 무작위 글자예요.",
      aip:"<b>자동 배정</b> · 부두 몫의 주소 대역에서 배선(CNI)이 골라 준 Pod IP예요. Pod가 새로 만들어지면 바뀌어요.",
      acip:"<b>자동 배정</b> · Service 주소 대역에서 하나 배정된 고정 주소예요. Service를 지우지 않는 한 그대로예요.",
      arv:"<b>자동 생성</b> · 장부가 바뀔 때마다 올라가는 버전 번호예요.",
      acid:"<b>자동 생성</b> · 실행 엔진이 붙인 컨테이너 ID예요."
    }
  }
};
})();
